# Generated by Django 3.1.3 on 2020-11-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valores_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valor',
            old_name='acumulado',
            new_name='acumulado_porciento',
        ),
        migrations.RenameField(
            model_name='valor',
            old_name='variacion',
            new_name='variacion_porciento',
        ),
        migrations.AlterField(
            model_name='valor',
            name='actualizacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='valor',
            name='volumen',
            field=models.IntegerField(),
        ),
    ]
