# Generated by Django 3.1.3 on 2020-11-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valores_app', '0002_auto_20201125_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valor',
            old_name='acumulado_porciento',
            new_name='ultimo',
        ),
    ]
